/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RobertoPruebas;

import Excepciones.*;
import Ventanas.selectorProductofac;
import Ventanas.selectorSucursal;
import java.awt.Color;
import java.nio.channels.Selector;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberto
 */
public class consultaFactura extends javax.swing.JPanel {

    private final Conexion Conexion_DB = new Conexion();
    private selectorSucursal Selector;
    private String[] Sucursal;
    private int id;
    /**
     * Creates new form consultaFactura
     */
    public consultaFactura() {
        initComponents();
    }
        private void setFactura(){
        lbl_Nombre.setText("FACTURA NO:");
        lbl_Correlativo.setText(Sucursal[1]);
        btn_Factura.setBackground(Color.RED);
    }
    private void Cliente(String nit){
        try {
            String[] Cliente = Conexion_DB.obtenerCliente(nit);
            txt_Nit.setText(Cliente[1]);
            txt_Nombre.setText(Cliente[2]);
            txt_Apellido.setText(Cliente[3]);
            txt_Descuento.setText(Cliente[4]);
            txt_Direccion.setText(Cliente[5]);
            if (Float.parseFloat(Cliente[6]) > 0) {
                rbtn_Credito.setEnabled(true);
                rbtn_Credito.setSelected(true);
            }else {
                rbtn_Credito.setEnabled(false);
                rbtn_Credito.setSelected(false);
            }
            
        } catch (SQLException|NoSePuedeConectar ex) {
            DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", ex.getMessage());
            dialogo.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Correlativo = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        btn_Sucursal = new javax.swing.JLabel();
        btn_Factura = new javax.swing.JLabel();
        lbl_Fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sep_Nombre = new javax.swing.JSeparator();
        txt_Nit = new javax.swing.JTextField();
        btn_Seleccion = new javax.swing.JLabel();
        lbl_Nombre1 = new javax.swing.JLabel();
        txt_Direccion = new javax.swing.JTextField();
        lbl_Nombre2 = new javax.swing.JLabel();
        sep_Nombre1 = new javax.swing.JSeparator();
        lbl_Nombre3 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        sep_Nombre2 = new javax.swing.JSeparator();
        rbtn_Credito = new javax.swing.JRadioButton();
        txt_Apellido = new javax.swing.JTextField();
        lbl_Nombre4 = new javax.swing.JLabel();
        sep_Nombre3 = new javax.swing.JSeparator();
        lbl_Nombre5 = new javax.swing.JLabel();
        btn_Seleccion1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detalle = new javax.swing.JTable();
        lbl_Nombre6 = new javax.swing.JLabel();
        txt_Nombre4 = new javax.swing.JTextField();
        sep_Nombre4 = new javax.swing.JSeparator();
        lbl_Nombre7 = new javax.swing.JLabel();
        txt_Nombre5 = new javax.swing.JTextField();
        sep_Nombre5 = new javax.swing.JSeparator();
        sep_Nombre6 = new javax.swing.JSeparator();
        lbl_Nombre8 = new javax.swing.JLabel();
        txt_Descuento = new javax.swing.JTextField();
        lbl_Nombre9 = new javax.swing.JLabel();
        sep_Nombre7 = new javax.swing.JSeparator();
        txt_Comentario = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Correlativo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Correlativo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Correlativo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Correlativo.setText("00001");
        jPanel1.add(lbl_Correlativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        lbl_Nombre.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_Nombre.setText("FACTURA NO:");
        jPanel1.add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 220, -1));

        btn_Sucursal.setBackground(new java.awt.Color(255, 0, 0));
        btn_Sucursal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_Sucursal.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Sucursal.setText("SUCURSAL");
        btn_Sucursal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Sucursal.setName(""); // NOI18N
        btn_Sucursal.setOpaque(true);
        btn_Sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SucursalMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -10, 260, 50));

        btn_Factura.setBackground(new java.awt.Color(0, 0, 0));
        btn_Factura.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_Factura.setForeground(new java.awt.Color(255, 255, 255));
        btn_Factura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Factura.setText("BUSCAR FACTURA");
        btn_Factura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Factura.setName(""); // NOI18N
        btn_Factura.setOpaque(true);
        btn_Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FacturaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FacturaMouseEntered(evt);
            }
        });
        jPanel1.add(btn_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 180, 50));

        lbl_Fecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Fecha.setText("DD/MM/YYYY");
        jPanel1.add(lbl_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        sep_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, 10));

        txt_Nit.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Nit.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nit.setText("INGRESE EL NIT DEL CLIENTE");
        txt_Nit.setBorder(null);
        txt_Nit.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Nit.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Nit.setEnabled(false);
        txt_Nit.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Nit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NitFocusLost(evt);
            }
        });
        txt_Nit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NitMousePressed(evt);
            }
        });
        txt_Nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NitActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 26));

        btn_Seleccion.setBackground(new java.awt.Color(255, 0, 0));
        btn_Seleccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccion.setForeground(new java.awt.Color(255, 255, 255));
        btn_Seleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccion.setText("CONSULTA / EDITAR");
        btn_Seleccion.setOpaque(true);
        btn_Seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SeleccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SeleccionMouseEntered(evt);
            }
        });
        jPanel1.add(btn_Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 150, 30));

        lbl_Nombre1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre1.setText("NIT");
        jPanel1.add(lbl_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_Direccion.setEditable(false);
        txt_Direccion.setBackground(new java.awt.Color(0, 0, 0));
        txt_Direccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Direccion.setForeground(new java.awt.Color(255, 255, 255));
        txt_Direccion.setText("INGRESE LA DIRECCION DEL CLIENTE");
        txt_Direccion.setBorder(null);
        txt_Direccion.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Direccion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Direccion.setEnabled(false);
        txt_Direccion.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Direccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DireccionFocusLost(evt);
            }
        });
        txt_Direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_DireccionMousePressed(evt);
            }
        });
        txt_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 26));

        lbl_Nombre2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre2.setText("DIRECCION");
        jPanel1.add(lbl_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        sep_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 550, 10));

        lbl_Nombre3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre3.setText("NOMBRE");
        jPanel1.add(lbl_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        txt_Nombre.setEditable(false);
        txt_Nombre.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nombre.setText("INGRESE  EL NOMBRE DEL CLIENTE");
        txt_Nombre.setBorder(null);
        txt_Nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Nombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Nombre.setEnabled(false);
        txt_Nombre.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NombreFocusLost(evt);
            }
        });
        txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NombreMousePressed(evt);
            }
        });
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 300, 26));

        sep_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 300, 10));

        rbtn_Credito.setBackground(new java.awt.Color(0, 0, 0));
        rbtn_Credito.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbtn_Credito.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_Credito.setSelected(true);
        rbtn_Credito.setText("CREDITO");
        rbtn_Credito.setBorder(null);
        jPanel1.add(rbtn_Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, 90, 30));

        txt_Apellido.setEditable(false);
        txt_Apellido.setBackground(new java.awt.Color(0, 0, 0));
        txt_Apellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_Apellido.setText("INGRESE  EL APELLIDO DEL CLIENTE ");
        txt_Apellido.setBorder(null);
        txt_Apellido.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Apellido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Apellido.setEnabled(false);
        txt_Apellido.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ApellidoFocusLost(evt);
            }
        });
        txt_Apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ApellidoMousePressed(evt);
            }
        });
        txt_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 300, 26));

        lbl_Nombre4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre4.setText("VENDEDOR");
        jPanel1.add(lbl_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        sep_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 300, 10));

        lbl_Nombre5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre5.setText("TELEFONO");
        jPanel1.add(lbl_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        btn_Seleccion1.setBackground(new java.awt.Color(255, 0, 0));
        btn_Seleccion1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccion1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Seleccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccion1.setText("GUARDAR");
        btn_Seleccion1.setOpaque(true);
        btn_Seleccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Seleccion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Seleccion1MouseEntered(evt);
            }
        });
        jPanel1.add(btn_Seleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, 90, 40));

        tabla_detalle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabla_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_detalle.setEnabled(false);
        tabla_detalle.setGridColor(new java.awt.Color(0, 0, 0));
        tabla_detalle.setRowHeight(24);
        tabla_detalle.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tabla_detalle.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabla_detalle.setShowVerticalLines(false);
        tabla_detalle.getTableHeader().setReorderingAllowed(false);
        tabla_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_detalleMousePressed(evt);
            }
        });
        tabla_detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_detalleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_detalleKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_detalle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 940, 360));

        lbl_Nombre6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre6.setText("DESCUENTO");
        jPanel1.add(lbl_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, -1, -1));

        txt_Nombre4.setEditable(false);
        txt_Nombre4.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nombre4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nombre4.setText("SELECCIONE UNO");
        txt_Nombre4.setBorder(null);
        txt_Nombre4.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Nombre4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Nombre4.setEnabled(false);
        txt_Nombre4.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Nombre4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Nombre4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Nombre4FocusLost(evt);
            }
        });
        txt_Nombre4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Nombre4MousePressed(evt);
            }
        });
        txt_Nombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre4ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, 26));

        sep_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 340, 10));

        lbl_Nombre7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre7.setText("VENDEDOR");
        jPanel1.add(lbl_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txt_Nombre5.setEditable(false);
        txt_Nombre5.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nombre5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nombre5.setText("INGRESE  EL CODIGO Ó SELECCIONE UNO");
        txt_Nombre5.setBorder(null);
        txt_Nombre5.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Nombre5.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Nombre5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Nombre5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Nombre5FocusLost(evt);
            }
        });
        txt_Nombre5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Nombre5MousePressed(evt);
            }
        });
        txt_Nombre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre5ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, 26));

        sep_Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 340, 10));

        sep_Nombre6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 60, 10));

        lbl_Nombre8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre8.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre8.setText("APELLIDO");
        jPanel1.add(lbl_Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        txt_Descuento.setBackground(new java.awt.Color(0, 0, 0));
        txt_Descuento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Descuento.setForeground(new java.awt.Color(255, 255, 255));
        txt_Descuento.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Descuento.setText("0.00");
        txt_Descuento.setBorder(null);
        txt_Descuento.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Descuento.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Descuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DescuentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DescuentoFocusLost(evt);
            }
        });
        txt_Descuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_DescuentoMousePressed(evt);
            }
        });
        txt_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescuentoActionPerformed(evt);
            }
        });
        txt_Descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DescuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescuentoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 60, 26));

        lbl_Nombre9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre9.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre9.setText("COMENTARIO");
        jPanel1.add(lbl_Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, 40));

        sep_Nombre7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 340, 10));

        txt_Comentario.setBackground(new java.awt.Color(0, 0, 0));
        txt_Comentario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Comentario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Comentario.setText("INGRESE UN NUMERO DE ORDEN O UN COMENTARIO");
        txt_Comentario.setBorder(null);
        txt_Comentario.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Comentario.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Comentario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ComentarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ComentarioFocusLost(evt);
            }
        });
        txt_Comentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ComentarioMousePressed(evt);
            }
        });
        txt_Comentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ComentarioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NitFocusGained
        if (txt_Nit.getText().equals("INGRESE EL NIT DEL CLIENTE")) txt_Nit.setText("");
    }//GEN-LAST:event_txt_NitFocusGained

    private void txt_NitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NitFocusLost
        if (txt_Nit.getText().equals("")) txt_Nit.setText("INGRESE EL NIT DEL CLIENTE");
        else{
            try {
                if (Conexion_DB.existeCliente(txt_Nit.getText())) {
                    Cliente(txt_Nit.getText());
                }else{
                    txt_Nombre.setText("");
                    txt_Nombre.setEditable(true);
                    txt_Apellido.setText("");
                    txt_Apellido.setEditable(true);
                    txt_Direccion.setText("");
                    txt_Direccion.setEditable(true);
                    txt_Descuento.setText("0");
                }
            } catch (SQLException|NoSePuedeConectar ex) {
                DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", ex.getMessage());
                dialogo.setVisible(true);
            }
        }
    }//GEN-LAST:event_txt_NitFocusLost

    private void txt_NitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NitMousePressed

    private void txt_NitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NitActionPerformed

    private void btn_SeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionMouseClicked

    }//GEN-LAST:event_btn_SeleccionMouseClicked

    private void btn_SeleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SeleccionMouseEntered

    private void txt_DireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DireccionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionFocusGained

    private void txt_DireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionFocusLost

    private void txt_DireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DireccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionMousePressed

    private void txt_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionActionPerformed

    private void txt_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreFocusGained

    private void txt_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreFocusLost

    private void txt_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreMousePressed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_ApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ApellidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoFocusGained

    private void txt_ApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoFocusLost

    private void txt_ApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ApellidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoMousePressed

    private void txt_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoActionPerformed

    private void btn_Seleccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Seleccion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Seleccion1MouseClicked

    private void btn_Seleccion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Seleccion1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Seleccion1MouseEntered

    private void tabla_detalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_detalleMousePressed

    }//GEN-LAST:event_tabla_detalleMousePressed

    private void tabla_detalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_detalleKeyPressed

    }//GEN-LAST:event_tabla_detalleKeyPressed

    private void tabla_detalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_detalleKeyReleased

    }//GEN-LAST:event_tabla_detalleKeyReleased

    private void txt_Nombre4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nombre4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre4FocusGained

    private void txt_Nombre4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nombre4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre4FocusLost

    private void txt_Nombre4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Nombre4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre4MousePressed

    private void txt_Nombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre4ActionPerformed

    private void txt_Nombre5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nombre5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre5FocusGained

    private void txt_Nombre5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nombre5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre5FocusLost

    private void txt_Nombre5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Nombre5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre5MousePressed

    private void txt_Nombre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre5ActionPerformed

    private void txt_DescuentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DescuentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoFocusGained

    private void txt_DescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DescuentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoFocusLost

    private void txt_DescuentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DescuentoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoMousePressed

    private void txt_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoActionPerformed

    private void txt_DescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescuentoKeyReleased

    }//GEN-LAST:event_txt_DescuentoKeyReleased

    private void txt_DescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescuentoKeyTyped
        if ((evt.getKeyCode()>= 48) && (evt.getKeyCode()<=57)/* || !(evt.getKeyCode() == 46)*/) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_DescuentoKeyTyped

    private void txt_ComentarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ComentarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComentarioFocusGained

    private void txt_ComentarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ComentarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComentarioFocusLost

    private void txt_ComentarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ComentarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComentarioMousePressed

    private void txt_ComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComentarioActionPerformed

    private void btn_FacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FacturaMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_FacturaMouseEntered

    private void btn_FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FacturaMouseClicked
        selectorFactura selector=new selectorFactura(null, true);
        selector.setVisible(true);
        String[] datos=selector.getDatos();
        if(datos!=null)
        {
            lbl_Correlativo.setText(datos[1]);
            txt_Nombre.setText(datos[2]);
            txt_Apellido.setText(datos[3]);
            txt_Nit.setText(datos[4]);
            txt_Nombre4.setText(datos[5]);
            lbl_Fecha.setText(datos[7]);
            btn_Sucursal.setText(datos[8].toUpperCase()+" SERIE: "+datos[6]);
            try {
                DefaultTableModel detalle=Conexion_DB.obtenerDetalleFactura(Integer.parseInt(datos[0]));
                if(detalle!=null)
                    tabla_detalle.setModel(detalle);
            } catch (SQLException|NoSePuedeConectar ex) {
                Logger.getLogger(consultaFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_FacturaMouseClicked

    private void btn_SucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SucursalMouseClicked

    }//GEN-LAST:event_btn_SucursalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Factura;
    private javax.swing.JLabel btn_Seleccion;
    private javax.swing.JLabel btn_Seleccion1;
    private javax.swing.JLabel btn_Sucursal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Correlativo;
    private javax.swing.JLabel lbl_Fecha;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Nombre1;
    private javax.swing.JLabel lbl_Nombre2;
    private javax.swing.JLabel lbl_Nombre3;
    private javax.swing.JLabel lbl_Nombre4;
    private javax.swing.JLabel lbl_Nombre5;
    private javax.swing.JLabel lbl_Nombre6;
    private javax.swing.JLabel lbl_Nombre7;
    private javax.swing.JLabel lbl_Nombre8;
    private javax.swing.JLabel lbl_Nombre9;
    private javax.swing.JRadioButton rbtn_Credito;
    private javax.swing.JSeparator sep_Nombre;
    private javax.swing.JSeparator sep_Nombre1;
    private javax.swing.JSeparator sep_Nombre2;
    private javax.swing.JSeparator sep_Nombre3;
    private javax.swing.JSeparator sep_Nombre4;
    private javax.swing.JSeparator sep_Nombre5;
    private javax.swing.JSeparator sep_Nombre6;
    private javax.swing.JSeparator sep_Nombre7;
    private javax.swing.JTable tabla_detalle;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Comentario;
    private javax.swing.JTextField txt_Descuento;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Nit;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Nombre4;
    private javax.swing.JTextField txt_Nombre5;
    // End of variables declaration//GEN-END:variables
}
