/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RobertoPruebas;

import Ventanas.selectorCliente;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberto
 */
public class DeudasTrabajador extends javax.swing.JPanel {
    private Conexion conexion;
    private int trabajadorActual=0;
    private boolean adelanto=true;
    int mes=0;
    /**
     * Creates new form Planilla
     * @param conexion
     */
    public DeudasTrabajador(Conexion conexion) {
        initComponents();
        this.conexion=conexion;
        try {
            mes=conexion.obtenerMesActual();
            switch(mes){
                case 1: lbl_nombre9.setText("Enero"); break;
                case 2: lbl_nombre9.setText("Febrero"); break;
                case 3: lbl_nombre9.setText("Marzo"); break;
                case 4: lbl_nombre9.setText("Abril"); break;
                case 5: lbl_nombre9.setText("Mayo"); break;
                case 6: lbl_nombre9.setText("Junio"); break;
                case 7: lbl_nombre9.setText("Julio"); break;
                case 8: lbl_nombre9.setText("Agosto"); break;
                case 9: lbl_nombre9.setText("Septiembre"); break;
                case 10: lbl_nombre9.setText("Octubre"); break;
                case 11: lbl_nombre9.setText("Noviembre"); break;
                default: lbl_nombre9.setText("Diciembre"); break;  
            }
            lbl_prestamoTotal.setVisible(!adelanto);
            ftx_prestamoTotal.setVisible(!adelanto);
        } catch (SQLException ex) {
            Logger.getLogger(DeudasTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * MEtodo para la insercion de prestamos, si para el mes actual no hay prestamos registrados
     * lo creo, si ya hay uno solo carga el monto
     * @throws SQLException 
     */
    private void insertarPrestamo() throws SQLException{
        double prestamoMes=conexion.obtenerPrestamoMes(trabajadorActual,false,false);//Carga el prestamo del mes 
        if(prestamoMes==0)//SI es igual a 0 crea el prestamo del mes
        {
            conexion.insertarAdelanto(trabajadorActual, Double.parseDouble(ftx_cantidad.getValue().toString()),false);
        }
        else{
            conexion.modificarAdelanto(trabajadorActual,Double.parseDouble(ftx_cantidad.getValue().toString()), false);
        }
        if(!adelanto)//SI la bandera indica que esta en la ventana deuda para cargar los datos de llos pretamos
        {
            recargarMontos();
            ftx_prestamoTotal.setValue(conexion.obtenerPrestamoMes(trabajadorActual,false, true));
            ftx_prestamoTotal.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_prestamoTotal.getValue().toString())));
        }
    }
    /**
     * Metodo que vuelve a cargar los datos a los campos de la deuda del mes y el monto
     * @throws SQLException 
     */
    private void recargarMontos() throws SQLException
    {
        ftx_deuda.setValue(conexion.obtenerPrestamoMes(trabajadorActual, adelanto,false));
        ftx_deuda.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_deuda.getValue().toString())));
        ftx_cantidad.setValue(0.00);
        ftx_cantidad.setText("Q0.00");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sep_Nombre = new javax.swing.JSeparator();
        txt_Nit = new javax.swing.JTextField();
        lbl_nit = new javax.swing.JLabel();
        btn_Seleccioncliente = new javax.swing.JLabel();
        btn_adelanto = new javax.swing.JLabel();
        btn_prestamo = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        sep_Nombre1 = new javax.swing.JSeparator();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        sep_Nombre2 = new javax.swing.JSeparator();
        lbl_nombre1 = new javax.swing.JLabel();
        sep_Nombre3 = new javax.swing.JSeparator();
        lbl_nombre2 = new javax.swing.JLabel();
        sep_Nombre4 = new javax.swing.JSeparator();
        lbl_nombre3 = new javax.swing.JLabel();
        sep_Nombre5 = new javax.swing.JSeparator();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        ftx_bono = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        lbl_nombre4 = new javax.swing.JLabel();
        ftx_cantidad = new javax.swing.JFormattedTextField();
        sep_Nombre6 = new javax.swing.JSeparator();
        lbl_nombre5 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();
        ftx_deuda = new javax.swing.JFormattedTextField();
        sep_Nombre7 = new javax.swing.JSeparator();
        lbl_nombre7 = new javax.swing.JLabel();
        lbl_prestamo_adelantoMes = new javax.swing.JLabel();
        lbl_nombre9 = new javax.swing.JLabel();
        lbl_prestamoTotal = new javax.swing.JLabel();
        ftx_prestamoTotal = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(930, 650));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        sep_Nombre.setForeground(new java.awt.Color(255, 255, 255));

        txt_Nit.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Nit.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nit.setText("INGRESE EL NIT DEL CLIENTE");
        txt_Nit.setBorder(null);
        txt_Nit.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Nit.setPreferredSize(new java.awt.Dimension(271, 16));
        txt_Nit.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Nit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NitFocusLost(evt);
            }
        });
        txt_Nit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NitMousePressed(evt);
            }
        });
        txt_Nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NitActionPerformed(evt);
            }
        });

        lbl_nit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nit.setText("NIT");

        btn_Seleccioncliente.setBackground(new java.awt.Color(255, 0, 0));
        btn_Seleccioncliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccioncliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_Seleccioncliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccioncliente.setText("SELECCIONAR");
        btn_Seleccioncliente.setOpaque(true);
        btn_Seleccioncliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SeleccionclienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SeleccionclienteMouseEntered(evt);
            }
        });

        btn_adelanto.setBackground(new java.awt.Color(255, 0, 0));
        btn_adelanto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_adelanto.setForeground(new java.awt.Color(255, 255, 255));
        btn_adelanto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_adelanto.setText("ADELANTO");
        btn_adelanto.setName(""); // NOI18N
        btn_adelanto.setOpaque(true);
        btn_adelanto.setPreferredSize(new java.awt.Dimension(160, 40));
        btn_adelanto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adelantoMouseClicked(evt);
            }
        });

        btn_prestamo.setBackground(new java.awt.Color(0, 0, 0));
        btn_prestamo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_prestamo.setForeground(new java.awt.Color(255, 255, 255));
        btn_prestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_prestamo.setText("PRESTAMO");
        btn_prestamo.setName(""); // NOI18N
        btn_prestamo.setOpaque(true);
        btn_prestamo.setPreferredSize(new java.awt.Dimension(160, 40));
        btn_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseClicked(evt);
            }
        });

        txt_nombre.setBackground(new java.awt.Color(0, 0, 0));
        txt_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(null);
        txt_nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_nombre.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_nombre.setEnabled(false);
        txt_nombre.setPreferredSize(new java.awt.Dimension(271, 16));
        txt_nombre.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nombreFocusLost(evt);
            }
        });
        txt_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombreMousePressed(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        sep_Nombre1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("NOMBRE");

        lbl_apellido.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_apellido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apellido.setText("APELLIDO");

        txt_apellido.setBackground(new java.awt.Color(0, 0, 0));
        txt_apellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setBorder(null);
        txt_apellido.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_apellido.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_apellido.setEnabled(false);
        txt_apellido.setPreferredSize(new java.awt.Dimension(271, 16));
        txt_apellido.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_apellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_apellidoFocusLost(evt);
            }
        });
        txt_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_apellidoMousePressed(evt);
            }
        });
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });

        sep_Nombre2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre1.setText("SALARIO BASE");

        sep_Nombre3.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre2.setText("BONO INCENTIVO");

        sep_Nombre4.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre3.setText("COMISIÓN");

        sep_Nombre5.setForeground(new java.awt.Color(255, 255, 255));

        jFormattedTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        jFormattedTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextField1.setEnabled(false);
        jFormattedTextField1.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(271, 16));
        jFormattedTextField1.setValue(0.00);
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });

        ftx_bono.setBackground(new java.awt.Color(0, 0, 0));
        ftx_bono.setBorder(null);
        ftx_bono.setForeground(new java.awt.Color(255, 255, 255));
        ftx_bono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftx_bono.setCaretColor(new java.awt.Color(255, 255, 255));
        ftx_bono.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        ftx_bono.setEnabled(false);
        ftx_bono.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftx_bono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ftx_bono.setPreferredSize(new java.awt.Dimension(271, 16));
        ftx_bono.setValue(0.00);
        ftx_bono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftx_bonoFocusLost(evt);
            }
        });

        jFormattedTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jFormattedTextField3.setBorder(null);
        jFormattedTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        jFormattedTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextField3.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextField3.setEnabled(false);
        jFormattedTextField3.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextField3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jFormattedTextField3.setPreferredSize(new java.awt.Dimension(271, 16));
        jFormattedTextField3.setValue(0.00);
        jFormattedTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField3FocusLost(evt);
            }
        });
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        lbl_nombre4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre4.setText("ADELANTO");

        ftx_cantidad.setBackground(new java.awt.Color(0, 0, 0));
        ftx_cantidad.setBorder(null);
        ftx_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        ftx_cantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftx_cantidad.setCaretColor(new java.awt.Color(255, 255, 255));
        ftx_cantidad.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        ftx_cantidad.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftx_cantidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ftx_cantidad.setPreferredSize(new java.awt.Dimension(271, 16));
        ftx_cantidad.setSelectionColor(new java.awt.Color(255, 0, 0));
        ftx_cantidad.setValue(0.00);
        ftx_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftx_cantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftx_cantidadFocusLost(evt);
            }
        });

        sep_Nombre6.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre5.setText("MONTO PARA EL");

        btn_guardar.setBackground(new java.awt.Color(255, 0, 0));
        btn_guardar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_guardar.setText("GUARDAR");
        btn_guardar.setOpaque(true);
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guardarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_guardarMousePressed(evt);
            }
        });

        ftx_deuda.setBackground(new java.awt.Color(0, 0, 0));
        ftx_deuda.setBorder(null);
        ftx_deuda.setForeground(new java.awt.Color(255, 255, 255));
        ftx_deuda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftx_deuda.setCaretColor(new java.awt.Color(255, 255, 255));
        ftx_deuda.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        ftx_deuda.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftx_deuda.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ftx_deuda.setPreferredSize(new java.awt.Dimension(271, 16));
        ftx_deuda.setSelectionColor(new java.awt.Color(255, 0, 0));
        ftx_deuda.setValue(0.00);
        ftx_deuda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftx_deudaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftx_deudaFocusLost(evt);
            }
        });

        sep_Nombre7.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre7.setText("MES");

        lbl_prestamo_adelantoMes.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_prestamo_adelantoMes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prestamo_adelantoMes.setText("ADELANTO DEL MES");

        lbl_nombre9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nombre9.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre9.setText("MES");

        lbl_prestamoTotal.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_prestamoTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prestamoTotal.setText("PRESTAMO TOTAL");

        ftx_prestamoTotal.setBackground(new java.awt.Color(0, 0, 0));
        ftx_prestamoTotal.setBorder(null);
        ftx_prestamoTotal.setForeground(new java.awt.Color(255, 255, 255));
        ftx_prestamoTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftx_prestamoTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        ftx_prestamoTotal.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        ftx_prestamoTotal.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftx_prestamoTotal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ftx_prestamoTotal.setPreferredSize(new java.awt.Dimension(271, 16));
        ftx_prestamoTotal.setSelectionColor(new java.awt.Color(255, 0, 0));
        ftx_prestamoTotal.setValue(0.00);
        ftx_prestamoTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftx_prestamoTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftx_prestamoTotalFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_adelanto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btn_Seleccioncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_nit)
                            .addComponent(sep_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nit, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombre1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sep_Nombre3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_nombre)
                                .addComponent(sep_Nombre1)
                                .addComponent(lbl_nombre2)
                                .addComponent(sep_Nombre4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(ftx_bono, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_nombre3)
                            .addComponent(lbl_apellido)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(sep_Nombre2)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sep_Nombre5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sep_Nombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftx_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_prestamo_adelantoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_prestamoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftx_prestamoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sep_Nombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ftx_deuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addComponent(lbl_nombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_nombre9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sep_Nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_adelanto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_apellido)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sep_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sep_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_Seleccioncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_nombre))
                                    .addComponent(lbl_nit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Nit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(sep_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_nombre2)
                                .addComponent(lbl_nombre3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftx_bono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sep_Nombre3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sep_Nombre4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftx_deuda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_prestamo_adelantoMes)
                        .addComponent(lbl_nombre9)))
                .addGap(0, 0, 0)
                .addComponent(sep_Nombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ftx_prestamoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(lbl_prestamoTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre5)
                            .addComponent(ftx_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre4)
                            .addComponent(sep_Nombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NitFocusGained
        if (txt_Nit.getText().equals("INGRESE EL NIT DEL CLIENTE")) txt_Nit.setText("");
    }//GEN-LAST:event_txt_NitFocusGained

    private void txt_NitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NitFocusLost
        if (txt_Nit.getText().equals("")) txt_Nit.setText("INGRESE EL NIT DEL CLIENTE");
    }//GEN-LAST:event_txt_NitFocusLost

    private void txt_NitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NitMousePressed

    private void txt_NitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NitActionPerformed

    private void btn_SeleccionclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionclienteMouseClicked
        selectorTrabajador selector = new selectorTrabajador(null, true);
        selector.setVisible(true);
        String[] trabajador=selector.getTrabajador();
        if(trabajador!=null)
        {
            trabajadorActual=Integer.parseInt(trabajador[0]);
            txt_Nit.setText(trabajador[1]);
            txt_nombre.setText(trabajador[2]);
            txt_apellido.setText(trabajador[3]);
            jFormattedTextField1.setValue(Double.parseDouble(trabajador[4]));
            jFormattedTextField1.setText("Q"+String.format("%.2f",Double.parseDouble(trabajador[4])));
            ftx_bono.setValue(Double.parseDouble(trabajador[5]));
            ftx_bono.setText("Q"+String.format("%.2f",Double.parseDouble(trabajador[5])));
            try {
                ftx_deuda.setText("Q"+String.format("%.2f",conexion.obtenerPrestamoMes(trabajadorActual, adelanto,false)));
                if(!adelanto)
                {
                    ftx_prestamoTotal.setValue(conexion.obtenerPrestamoMes(trabajadorActual,false, true));
                    ftx_prestamoTotal.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_prestamoTotal.getValue().toString())));
                }
            } catch (SQLException ex) {
                Logger.getLogger(DeudasTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_SeleccionclienteMouseClicked

    private void btn_SeleccionclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionclienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SeleccionclienteMouseEntered

    private void btn_adelantoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adelantoMouseClicked
        adelanto=true;
        btn_adelanto.setBackground(Color.red);
        btn_prestamo.setBackground(Color.black);
        lbl_nombre4.setText("ADELANTO");
        lbl_prestamo_adelantoMes.setText("ADELANTO DEL MES");
        lbl_prestamoTotal.setVisible(!adelanto);
        ftx_prestamoTotal.setVisible(!adelanto);
        try {
            recargarMontos();
            
        } catch (SQLException ex) {
            Logger.getLogger(DeudasTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_adelantoMouseClicked

    private void btn_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseClicked
        // TODO add your handling code here:
        adelanto=false;
        btn_adelanto.setBackground(Color.black);
        btn_prestamo.setBackground(Color.red);
        lbl_prestamo_adelantoMes.setText("PRESTAMO DEL MES");
        lbl_nombre4.setText("PRESTAMO");
        lbl_prestamoTotal.setVisible(!adelanto);
        ftx_prestamoTotal.setVisible(!adelanto);
        try {
            recargarMontos();
            ftx_prestamoTotal.setValue(conexion.obtenerPrestamoMes(trabajadorActual,false, true));
            ftx_prestamoTotal.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_prestamoTotal.getValue().toString())));
        } catch (SQLException ex) {
            Logger.getLogger(DeudasTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_prestamoMouseClicked

    private void txt_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreFocusGained

    private void txt_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreFocusLost

    private void txt_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreMousePressed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_apellidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoFocusGained

    private void txt_apellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_apellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoFocusLost

    private void txt_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_apellidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoMousePressed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
        // TODO add your handling code here:   
        String cadena=jFormattedTextField1.getText();
        if(cadena.matches(("[+-]?\\d*(\\.\\d+)?")))
            jFormattedTextField1.setText("Q"+String.format("%.2f",Double.parseDouble(jFormattedTextField1.getText())));
        else
            jFormattedTextField1.setText("Q"+jFormattedTextField1.getValue().toString());
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    private void ftx_bonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_bonoFocusLost
        // TODO add your handling code here:
        String cadena=ftx_bono.getText();
        if(cadena.matches(("[+-]?\\d*(\\.\\d+)?")))
            ftx_bono.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_bono.getText())));
        else
            ftx_bono.setText("Q"+ftx_bono.getValue().toString());
    }//GEN-LAST:event_ftx_bonoFocusLost

    private void jFormattedTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3FocusLost

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void ftx_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_cantidadFocusLost
        // TODO add your handling code here:
        String cadena=ftx_cantidad.getText();
        if(cadena.matches(("[+-]?\\d*(\\.\\d+)?")))
            ftx_cantidad.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_cantidad.getText())));
        else
            ftx_cantidad.setText("Q"+ftx_cantidad.getValue().toString());
    }//GEN-LAST:event_ftx_cantidadFocusLost

    private void ftx_cantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_cantidadFocusGained
        // TODO add your handling code here:
        ftx_cantidad.setText(ftx_cantidad.getValue().toString());
    }//GEN-LAST:event_ftx_cantidadFocusGained

    /**
     * metodo que guarda los datos de las deudas en la base de datos
     * Compara si se esta manejando prestamos o adelantos, verifica si hay un trabajador cargado
     * Verifica si es necesario crear la deuda o prestamo, o solo modificarlos
     * Guarda los datos
     * @param evt 
     */
    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        try {
            if(trabajadorActual>0&&Double.parseDouble(ftx_cantidad.getValue().toString())>0)//Compara si hay datos de un trabajador cargados
            { 
                double deudaMes=conexion.obtenerPrestamoMes(trabajadorActual, adelanto,false);//Carga la deuda del mes actual
                if(adelanto){
                    if(deudaMes+Double.parseDouble(ftx_cantidad.getValue().toString())<=
                                Double.parseDouble(ftx_bono.getValue().toString())/2){//Si la deuda supera al la mitad del bono incentivo
                        //inserta los datos
                        if(deudaMes==0)
                        {
                            conexion.insertarAdelanto(trabajadorActual,
                            Double.parseDouble(ftx_cantidad.getValue().toString()), adelanto);
                        }
                        else
                        {
                            conexion.modificarAdelanto(trabajadorActual,
                            Double.parseDouble(ftx_cantidad.getValue().toString()), adelanto);
                        }
                        recargarMontos();
                    }
                    else
                    {
                        DialogoOpcion d=new DialogoOpcion(null,true,DialogoOpcion.ICONO_INTERROGANTE,"Monto muy grande",
                                "El monto es mayor al bono incentivo        quincenal, se guardara como prestamo");
                        d.setVisible(adelanto);
                        if(d.isAceptar()){
                        insertarPrestamo();
                        recargarMontos();
                        }
                    }
                }
                else
                    insertarPrestamo();
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeudasTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarMouseEntered

    private void btn_guardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMousePressed
        // TODO add your handling code here:
        btn_guardar.requestFocus();
    }//GEN-LAST:event_btn_guardarMousePressed

    private void ftx_deudaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_deudaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ftx_deudaFocusGained

    private void ftx_deudaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_deudaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ftx_deudaFocusLost

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void ftx_prestamoTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_prestamoTotalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ftx_prestamoTotalFocusGained

    private void ftx_prestamoTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_prestamoTotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ftx_prestamoTotalFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Seleccioncliente;
    private javax.swing.JLabel btn_adelanto;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel btn_prestamo;
    private javax.swing.JFormattedTextField ftx_bono;
    private javax.swing.JFormattedTextField ftx_cantidad;
    private javax.swing.JFormattedTextField ftx_deuda;
    private javax.swing.JFormattedTextField ftx_prestamoTotal;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombre1;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_nombre3;
    private javax.swing.JLabel lbl_nombre4;
    private javax.swing.JLabel lbl_nombre5;
    private javax.swing.JLabel lbl_nombre7;
    private javax.swing.JLabel lbl_nombre9;
    private javax.swing.JLabel lbl_prestamoTotal;
    private javax.swing.JLabel lbl_prestamo_adelantoMes;
    private javax.swing.JSeparator sep_Nombre;
    private javax.swing.JSeparator sep_Nombre1;
    private javax.swing.JSeparator sep_Nombre2;
    private javax.swing.JSeparator sep_Nombre3;
    private javax.swing.JSeparator sep_Nombre4;
    private javax.swing.JSeparator sep_Nombre5;
    private javax.swing.JSeparator sep_Nombre6;
    private javax.swing.JSeparator sep_Nombre7;
    private javax.swing.JTextField txt_Nit;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
