/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RobertoPruebas;

import Excepciones.*;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberto
 */
public class Productos extends javax.swing.JPanel {
    private Conexion conexion=new Conexion();
    private ArrayList[] sucursales_unidades;
    private ArrayList productoActual=new ArrayList(); 
    private boolean nuevo=false;
    private boolean modificar=false;
    /**
     * Creates new form Productos
     * @param conexion
     */
    public Productos(Conexion conexion) {
        initComponents();
        this.conexion=conexion;
        buttonGroup1.add(rbtn_Credito);
        buttonGroup1.add(rbtn_Credito1);
        buttonGroup1.add(rbtn_Credito2);
        try {
            sucursales_unidades=new ArrayList[2];
            sucursales_unidades=conexion.obtener_Sucursales_Unidades();
            for(int i=0; i<sucursales_unidades[0].size();i++)
            {
                cmb_sucursal.addItem(sucursales_unidades[1].get(i).toString());
            }
            for(int i=0; i<sucursales_unidades[2].size();i++)
            {
                cmb_unidad.addItem(sucursales_unidades[3].get(i).toString());
            }
            cmb_unidad.addItem("Ninguno");
            cmb_unidad.setSelectedIndex(cmb_unidad.getItemCount()-1);
            cambiarModo();
            llenarListado();
            setJTexFieldChanged(txt_codigo1);
            scp_listado.getViewport().setBackground(Color.red);
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnContenido = new javax.swing.JPanel();
        pnDetalle = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_codigoBarra = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_precioVenta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_codigoBarra = new javax.swing.JTextField();
        txt_venta = new javax.swing.JTextField();
        txt_costo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_estanteria = new javax.swing.JTextField();
        txt_columna = new javax.swing.JTextField();
        txt_fila = new javax.swing.JTextField();
        txt_existencia = new javax.swing.JTextField();
        cmb_unidad = new javax.swing.JComboBox<>();
        cmb_sucursal = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        scp_descripcion = new javax.swing.JScrollPane();
        txa_descripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btn_Guardar_Aceptar = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        scp_listado = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        rbtn_Credito = new javax.swing.JRadioButton();
        rbtn_Credito1 = new javax.swing.JRadioButton();
        rbtn_Credito2 = new javax.swing.JRadioButton();
        txt_codigo1 = new javax.swing.JTextField();
        lbl_codigo1 = new javax.swing.JLabel();
        pn_herramientas = new javax.swing.JPanel();
        btn_ver = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        Salir1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(950, 690));
        setMinimumSize(new java.awt.Dimension(950, 690));
        setName("detallesPN"); // NOI18N
        setPreferredSize(new java.awt.Dimension(940, 690));

        pnContenido.setBackground(new java.awt.Color(0, 0, 0));
        pnContenido.setMinimumSize(new java.awt.Dimension(150, 150));
        pnContenido.setPreferredSize(new java.awt.Dimension(840, 650));

        pnDetalle.setBackground(new java.awt.Color(0, 0, 0));
        pnDetalle.setForeground(new java.awt.Color(255, 255, 255));
        pnDetalle.setAlignmentX(0.0F);
        pnDetalle.setAlignmentY(0.0F);
        pnDetalle.setMaximumSize(new java.awt.Dimension(150, 150));
        pnDetalle.setMinimumSize(new java.awt.Dimension(150, 150));
        pnDetalle.setPreferredSize(new java.awt.Dimension(900, 650));

        lbl_Titulo.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo.setText("PRODUCTOS");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_codigoBarra.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_codigoBarra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_codigoBarra.setText("Codigo de barras");

        lbl_codigo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_codigo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_codigo.setText("Codigo");
        lbl_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_codigoMouseClicked(evt);
            }
        });

        lbl_precioVenta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_precioVenta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_precioVenta.setText("Precio de Venta");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descripción");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio Costo");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Columna");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fila");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Marca");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Existencia");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sucursal");

        txt_codigo.setBackground(new java.awt.Color(0, 0, 0));
        txt_codigo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_codigo.setForeground(new java.awt.Color(255, 255, 255));
        txt_codigo.setText("NO DISPONIBLE");
        txt_codigo.setBorder(null);
        txt_codigo.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_codigo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigoFocusLost(evt);
            }
        });
        txt_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_codigoMousePressed(evt);
            }
        });
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        txt_codigoBarra.setBackground(new java.awt.Color(0, 0, 0));
        txt_codigoBarra.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_codigoBarra.setForeground(new java.awt.Color(255, 255, 255));
        txt_codigoBarra.setText("NO DISPONIBLE");
        txt_codigoBarra.setBorder(null);
        txt_codigoBarra.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_codigoBarra.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_codigoBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigoBarraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigoBarraFocusLost(evt);
            }
        });
        txt_codigoBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_codigoBarraMousePressed(evt);
            }
        });
        txt_codigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoBarraActionPerformed(evt);
            }
        });

        txt_venta.setBackground(new java.awt.Color(0, 0, 0));
        txt_venta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_venta.setForeground(new java.awt.Color(255, 255, 255));
        txt_venta.setText("NO DISPONIBLE");
        txt_venta.setBorder(null);
        txt_venta.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_venta.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_venta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ventaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ventaFocusLost(evt);
            }
        });
        txt_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ventaMousePressed(evt);
            }
        });
        txt_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ventaActionPerformed(evt);
            }
        });

        txt_costo.setBackground(new java.awt.Color(0, 0, 0));
        txt_costo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_costo.setForeground(new java.awt.Color(255, 255, 255));
        txt_costo.setText("NO DISPONIBLE");
        txt_costo.setBorder(null);
        txt_costo.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_costo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_costo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_costoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_costoFocusLost(evt);
            }
        });
        txt_costo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_costoMousePressed(evt);
            }
        });
        txt_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_costoActionPerformed(evt);
            }
        });

        txt_marca.setBackground(new java.awt.Color(0, 0, 0));
        txt_marca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_marca.setForeground(new java.awt.Color(255, 255, 255));
        txt_marca.setText("NO DISPONIBLE");
        txt_marca.setBorder(null);
        txt_marca.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_marca.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_marcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_marcaFocusLost(evt);
            }
        });
        txt_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_marcaMousePressed(evt);
            }
        });
        txt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marcaActionPerformed(evt);
            }
        });

        txt_estanteria.setBackground(new java.awt.Color(0, 0, 0));
        txt_estanteria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_estanteria.setForeground(new java.awt.Color(255, 255, 255));
        txt_estanteria.setText("NO DISPONIBLE");
        txt_estanteria.setBorder(null);
        txt_estanteria.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_estanteria.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_estanteria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_estanteriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_estanteriaFocusLost(evt);
            }
        });
        txt_estanteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_estanteriaMousePressed(evt);
            }
        });
        txt_estanteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estanteriaActionPerformed(evt);
            }
        });

        txt_columna.setBackground(new java.awt.Color(0, 0, 0));
        txt_columna.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_columna.setForeground(new java.awt.Color(255, 255, 255));
        txt_columna.setText("NO DISPONIBLE");
        txt_columna.setBorder(null);
        txt_columna.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_columna.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_columna.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_columnaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_columnaFocusLost(evt);
            }
        });
        txt_columna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_columnaMousePressed(evt);
            }
        });
        txt_columna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_columnaActionPerformed(evt);
            }
        });

        txt_fila.setBackground(new java.awt.Color(0, 0, 0));
        txt_fila.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_fila.setForeground(new java.awt.Color(255, 255, 255));
        txt_fila.setText("NO DISPONIBLE");
        txt_fila.setBorder(null);
        txt_fila.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_fila.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_fila.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_filaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_filaFocusLost(evt);
            }
        });
        txt_fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_filaMousePressed(evt);
            }
        });
        txt_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filaActionPerformed(evt);
            }
        });

        txt_existencia.setBackground(new java.awt.Color(0, 0, 0));
        txt_existencia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_existencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_existencia.setText("NO DISPONIBLE");
        txt_existencia.setBorder(null);
        txt_existencia.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_existencia.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_existencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_existenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_existenciaFocusLost(evt);
            }
        });
        txt_existencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_existenciaMousePressed(evt);
            }
        });
        txt_existencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_existenciaActionPerformed(evt);
            }
        });

        cmb_unidad.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmb_unidad.setBorder(null);
        cmb_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_unidadActionPerformed(evt);
            }
        });

        cmb_sucursal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmb_sucursal.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Estanteria");

        txa_descripcion.setBackground(new java.awt.Color(0, 0, 0));
        txa_descripcion.setColumns(20);
        txa_descripcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txa_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        txa_descripcion.setLineWrap(true);
        txa_descripcion.setRows(5);
        txa_descripcion.setBorder(null);
        txa_descripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        txa_descripcion.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        scp_descripcion.setViewportView(txa_descripcion);

        jPanel1.setPreferredSize(new java.awt.Dimension(193, 193));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        btn_Guardar_Aceptar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Guardar_Aceptar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_Guardar_Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar_Aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Guardar_Aceptar.setText("GUARDAR");
        btn_Guardar_Aceptar.setName(""); // NOI18N
        btn_Guardar_Aceptar.setOpaque(true);
        btn_Guardar_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Guardar_AceptarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Guardar_AceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Guardar_AceptarMouseReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Unidades");

        scp_listado.setBorder(null);
        scp_listado.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scp_listado.setPreferredSize(new java.awt.Dimension(292, 615));

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_productos.setAutoscrolls(false);
        tbl_productos.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tbl_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productosMouseClicked(evt);
            }
        });
        scp_listado.setViewportView(tbl_productos);

        rbtn_Credito.setBackground(new java.awt.Color(0, 0, 0));
        rbtn_Credito.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbtn_Credito.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_Credito.setSelected(true);
        rbtn_Credito.setText("CÓDIGO");
        rbtn_Credito.setBorder(null);
        rbtn_Credito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_CreditoStateChanged(evt);
            }
        });
        rbtn_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_CreditoActionPerformed(evt);
            }
        });

        rbtn_Credito1.setBackground(new java.awt.Color(0, 0, 0));
        rbtn_Credito1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbtn_Credito1.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_Credito1.setSelected(true);
        rbtn_Credito1.setText("BARRAS");
        rbtn_Credito1.setBorder(null);
        rbtn_Credito1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_Credito1StateChanged(evt);
            }
        });

        rbtn_Credito2.setBackground(new java.awt.Color(0, 0, 0));
        rbtn_Credito2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbtn_Credito2.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_Credito2.setSelected(true);
        rbtn_Credito2.setText("DESCRIPCION");
        rbtn_Credito2.setBorder(null);
        rbtn_Credito2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_Credito2StateChanged(evt);
            }
        });
        rbtn_Credito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Credito2ActionPerformed(evt);
            }
        });

        txt_codigo1.setBackground(new java.awt.Color(0, 0, 0));
        txt_codigo1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        txt_codigo1.setForeground(new java.awt.Color(255, 255, 255));
        txt_codigo1.setBorder(null);
        txt_codigo1.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_codigo1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txt_codigo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigo1FocusLost(evt);
            }
        });
        txt_codigo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_codigo1MousePressed(evt);
            }
        });
        txt_codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo1ActionPerformed(evt);
            }
        });

        lbl_codigo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_codigo1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_codigo1.setText("FILTRO");
        lbl_codigo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_codigo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDetalleLayout = new javax.swing.GroupLayout(pnDetalle);
        pnDetalle.setLayout(pnDetalleLayout);
        pnDetalleLayout.setHorizontalGroup(
            pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetalleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnDetalleLayout.createSequentialGroup()
                                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_codigo)
                                            .addComponent(lbl_codigoBarra)
                                            .addComponent(lbl_precioVenta)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16))
                                        .addGap(19, 19, 19)
                                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_estanteria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                    .addComponent(txt_codigoBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDetalleLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(23, 23, 23)
                                        .addComponent(txt_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(txt_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnDetalleLayout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_existencia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel17)
                                            .addGap(14, 14, 14)
                                            .addComponent(cmb_unidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnDetalleLayout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                            .addComponent(cmb_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnDetalleLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(64, 64, 64)
                                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Guardar_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scp_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addComponent(rbtn_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn_Credito1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_Credito2))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addComponent(lbl_codigo1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scp_listado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbl_Titulo))
                .addGap(0, 0, 0))
        );
        pnDetalleLayout.setVerticalGroup(
            pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetalleLayout.createSequentialGroup()
                .addComponent(lbl_Titulo)
                .addGap(9, 9, 9)
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtn_Credito)
                        .addComponent(rbtn_Credito2)
                        .addComponent(rbtn_Credito1)))
                .addGap(2, 2, 2)
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codigo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addComponent(lbl_codigo)
                                .addGap(10, 10, 10)
                                .addComponent(lbl_codigoBarra)
                                .addGap(10, 10, 10)
                                .addComponent(lbl_precioVenta)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel16))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txt_codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txt_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txt_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txt_estanteria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel14))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txt_existencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel17))
                            .addComponent(cmb_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cmb_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGap(6, 6, 6)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(scp_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Guardar_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 62, Short.MAX_VALUE))
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addComponent(scp_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(0, 0, 0))))
        );

        javax.swing.GroupLayout pnContenidoLayout = new javax.swing.GroupLayout(pnContenido);
        pnContenido.setLayout(pnContenidoLayout);
        pnContenidoLayout.setHorizontalGroup(
            pnContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnContenidoLayout.setVerticalGroup(
            pnContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pn_herramientas.setBackground(new java.awt.Color(0, 0, 0));
        pn_herramientas.setPreferredSize(new java.awt.Dimension(868, 40));
        pn_herramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ver.setBackground(new java.awt.Color(255, 0, 0));
        btn_ver.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_ver.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ver.setText("VER");
        btn_ver.setName(""); // NOI18N
        btn_ver.setOpaque(true);
        btn_ver.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_verMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_verMouseReleased(evt);
            }
        });
        pn_herramientas.add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 138, -1));

        btn_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        btn_nuevo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setText("NUEVO");
        btn_nuevo.setName(""); // NOI18N
        btn_nuevo.setOpaque(true);
        btn_nuevo.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_nuevoMousePressed(evt);
            }
        });
        pn_herramientas.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 0, 138, -1));

        btn_modificar.setBackground(new java.awt.Color(0, 0, 0));
        btn_modificar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificar.setText(" MODIFICAR");
        btn_modificar.setName(""); // NOI18N
        btn_modificar.setOpaque(true);
        btn_modificar.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_modificarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modificarMouseReleased(evt);
            }
        });
        pn_herramientas.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 0, 138, -1));

        btn_eliminar.setBackground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.setName(""); // NOI18N
        btn_eliminar.setOpaque(true);
        btn_eliminar.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eliminarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseReleased(evt);
            }
        });
        pn_herramientas.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 0, 138, -1));

        Salir1.setBackground(new java.awt.Color(0, 0, 0));
        Salir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/cancel (2).png"))); // NOI18N
        Salir1.setOpaque(true);
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });
        pn_herramientas.add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(pnContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
            .addComponent(pn_herramientas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 948, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
    private void llenarListado()
    {
        try {
            int filtro;
            if(rbtn_Credito.isSelected())
                filtro=0;
            else if(rbtn_Credito1.isSelected())
                filtro=1;
            else
                filtro=2;
            DefaultTableModel tabla=conexion.obtenerProductos_vista(filtro,txt_codigo1.getText());
            if(tabla!=null)
                    tbl_productos.setModel(tabla);
                    /*//if(!nuevo){
                    ArrayList[] listado=null;
                    try {
                    listado=conexion.obtener_productos();
                    } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(listado!=null)
                    {
                    pn_listado.removeAll();
                    for(int i=0;i<listado[0].size();i++)
                    {
                    JPanel pan=new producto_lista(listado[1].get(i).toString(),listado[2].get(i).toString(),
                    listado[3].get(i).toString(),this);
                    pan.setSize(292,100);
                    pan.setLocation(0, i*100);
                    pan.setName(listado[0].get(i).toString());
                    pn_listado.add(pan);
                    }
                    pn_listado.setPreferredSize(new Dimension(pn_listado.getParent().getWidth(),listado[0].size()*100));
                    pn_listado.getParent().revalidate();
                    pn_listado.getParent().repaint();
                    }
                    //}*/
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void cambiarModo(){
        txt_codigo.setEnabled(nuevo);      
        txt_columna.setEnabled(nuevo||modificar);
        txt_costo.setEnabled(nuevo||modificar);
        txt_estanteria.setEnabled(nuevo||modificar);
        txt_existencia.setEnabled(nuevo);
        txt_fila.setEnabled(nuevo||modificar);
        txt_marca.setEnabled(nuevo||modificar);
        txt_venta.setEnabled(nuevo||modificar);
        txa_descripcion.setEnabled(nuevo||modificar);  
        btn_Guardar_Aceptar.setVisible(nuevo||modificar);
        txt_codigoBarra.setEnabled(nuevo||modificar);
        cmb_sucursal.setEnabled(nuevo || !modificar);
        tbl_productos.setEnabled(!nuevo);
    }
    public void cargarProducto(int i)
    {
        try {
            productoActual=conexion.obtener_detalleProducto(i,0);
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(productoActual.size()>0)
            cargarProductoActual();
        else
            modoSinDatos();
    }
    public void cargarProducto(String codigo, String codigo_barras, String descripcion)
    {
        try {
            productoActual=conexion.obtener_detalleProducto(descripcion,codigo,codigo_barras);
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(productoActual.size()>0)
            cargarProductoActual();
        else
           modoSinDatos();
    }
    private void cargarProductoActual()
    {
        if(productoActual.size()>0 && !nuevo){
            txt_codigo.setText(productoActual.get(1).toString());
            txt_codigoBarra.setText(productoActual.get(2).toString());
            txa_descripcion.setText(productoActual.get(3).toString());
            txt_venta.setText(productoActual.get(4).toString());
            txt_costo.setText(productoActual.get(5).toString());
            if(productoActual.get(6)==null)
                txt_estanteria.setText("");
            else
                txt_estanteria.setText(productoActual.get(6).toString());
            if(productoActual.get(7)==null)
                txt_columna.setText("");
            else
                txt_columna.setText(productoActual.get(7).toString());
            if(productoActual.get(8)==null)
                txt_fila.setText("");
            else
                txt_fila.setText(productoActual.get(8).toString());
            if(productoActual.get(9)==null)
            {
                cmb_unidad.setSelectedIndex(cmb_unidad.getItemCount()-1);
                cmb_unidad.setEnabled(false);
            }
            else
            {
                cmb_unidad.setSelectedIndex(Integer.parseInt(productoActual.get(9).toString())-1);
                cmb_unidad.setEnabled(true);
            }
            if(productoActual.get(10)==null)
                txt_fila.setText("");
            else
                txt_marca.setText(productoActual.get(10).toString());
        }
        else
            modoSinDatos();
    }
    private void modoSinDatos()
    {
        txt_marca.setText("");
        txt_columna.setText("");
        txt_costo.setText("");
        txt_codigoBarra.setText("");
        txt_existencia.setText("");
        txt_fila.setText("");
        txt_venta.setText("");
        txt_codigo.setText("");
        txa_descripcion.setText("");
        txt_estanteria.setText("");
    }
    private void setJTexFieldChanged(JTextField txt)
    {
        DocumentListener documentListener = new DocumentListener() {
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }

        };
        txt.getDocument().addDocumentListener(documentListener);
    }
        private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            txt_filtroChanged();
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
            txt_filtroChanged();
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            txt_filtroChanged();
        }
    }
    private void txt_filtroChanged()
    {
        //Copiar el contenido del jtextfield al jlabel
        llenarListado();
    }
    private void txt_columnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_columnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaActionPerformed

    private void txt_columnaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_columnaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaMousePressed

    private void txt_columnaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_columnaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaFocusLost

    private void txt_columnaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_columnaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaFocusGained

    private void txt_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costoActionPerformed

    private void txt_costoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_costoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costoMousePressed

    private void txt_costoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_costoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costoFocusLost

    private void txt_costoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_costoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costoFocusGained

    private void txt_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ventaActionPerformed

    private void txt_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ventaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ventaMousePressed

    private void txt_ventaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ventaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ventaFocusLost

    private void txt_ventaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ventaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ventaFocusGained

    private void txt_codigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoBarraActionPerformed

    private void txt_codigoBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_codigoBarraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoBarraMousePressed

    private void txt_codigoBarraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoBarraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoBarraFocusLost

    private void txt_codigoBarraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoBarraFocusGained
        // TODO add your handling code here:   
    }//GEN-LAST:event_txt_codigoBarraFocusGained

    private void txt_filaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_filaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaFocusGained

    private void txt_filaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_filaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaFocusLost

    private void txt_filaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_filaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaMousePressed

    private void txt_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaActionPerformed

    private void txt_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaFocusGained

    private void txt_marcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaFocusLost

    private void txt_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_marcaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaMousePressed

    private void txt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaActionPerformed

    private void txt_estanteriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_estanteriaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaFocusGained

    private void txt_estanteriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_estanteriaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaFocusLost

    private void txt_estanteriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_estanteriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaMousePressed

    private void txt_estanteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estanteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaActionPerformed

    private void txt_existenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_existenciaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaFocusGained

    private void txt_existenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_existenciaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaFocusLost

    private void txt_existenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_existenciaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaMousePressed

    private void txt_existenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_existenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaActionPerformed

    private void btn_Guardar_AceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_AceptarMousePressed
        // TODO add your handling code here:
        btn_Guardar_Aceptar.setBackground(java.awt.Color.orange);
    }//GEN-LAST:event_btn_Guardar_AceptarMousePressed

    private void btn_Guardar_AceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_AceptarMouseReleased
        // TODO add your handling code here:
        btn_Guardar_Aceptar.setBackground(java.awt.Color.red);
    }//GEN-LAST:event_btn_Guardar_AceptarMouseReleased

    private void btn_Guardar_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_AceptarMouseClicked
        
        try {
            if(nuevo){
                String est=txt_estanteria.getText(), fil=txt_fila.getText(), 
                        col=txt_columna.getText(), uni=(cmb_unidad.getSelectedIndex()+1)+"";
                if(Integer.parseInt(uni)== cmb_unidad.getItemCount())
                {
                    uni=null;
                }
                conexion.insertarProducto(txt_codigo.getText(),txt_codigoBarra.getText(),
                    txa_descripcion.getText(),Double.parseDouble(txt_venta.getText()),
                    Double.parseDouble(txt_costo.getText()),est,col,fil,txt_marca.getText(),
                    uni,Integer.parseInt(sucursales_unidades[0].get(cmb_sucursal.getSelectedIndex()).toString()),
                    Double.parseDouble(txt_existencia.getText()));
                llenarListado();
                btn_verMouseClicked(evt); 
                }
            if(modificar){
                String est=txt_estanteria.getText(), fil=txt_fila.getText(), 
                        col=txt_columna.getText();
                conexion.modificarProducto(Integer.parseInt(productoActual.get(0).toString()),txt_codigo.getText(),txt_codigoBarra.getText(),
                    txa_descripcion.getText(),Double.parseDouble(txt_venta.getText()),
                    Double.parseDouble(txt_costo.getText()),est,col,fil,txt_marca.getText());
                 cargarProducto(Integer.parseInt(productoActual.get(0).toString()));
                 btn_verMouseClicked(evt);
                 llenarListado();
            }
        } catch (SQLException|NoSePuedeConectar ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Guardar_AceptarMouseClicked

    private void txt_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoFocusGained

    private void txt_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoFocusLost

    private void txt_codigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_codigoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoMousePressed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void lbl_codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_codigoMouseClicked
        // TODO add your handling code here:
        if(nuevo||modificar)
            txt_codigo.requestFocus();
    }//GEN-LAST:event_lbl_codigoMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        if(nuevo||modificar)
            txt_fila.requestFocus();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void cmb_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_unidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_unidadActionPerformed

    private void btn_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verMouseClicked
        // TODO add your handling code here:
        btn_modificar.setBackground(Color.black);
        btn_nuevo.setBackground(Color.black);
        btn_ver.setBackground(Color.red);
        modificar=false;
        nuevo=false;
        cargarProductoActual();
        cambiarModo();
        lbl_codigo.requestFocus();
    }//GEN-LAST:event_btn_verMouseClicked

    private void btn_verMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verMousePressed

    private void btn_verMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verMouseReleased

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
       if(productoActual.size()>0)
        {
            btn_eliminar.setBackground(Color.red);
            try {
                DialogoOpcion dialogo= new DialogoOpcion(null,true, DialogoOpcion.ICONO_INTERROGANTE,"Eliminar Producto", "Esta seguro de eliminar este producto");
                dialogo.setVisible(true);
                if(dialogo.isAceptar())
                {
                    if(conexion.obtenerExistencia(0,Integer.parseInt(productoActual.get(0).toString()))==0)
                        conexion.deshabilitarProducto(Integer.parseInt(productoActual.get(0).toString()));
                    else{
                        dialogo=new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR,"Error","Aun hay existencias del producto");
                        dialogo.setVisible(true);
                    }
                }
            } catch (SQLException|NoSePuedeConectar ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            btn_eliminar.setBackground(Color.black);
            llenarListado();
            productoActual=new ArrayList();
            modoSinDatos();
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_eliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarMousePressed

    private void btn_eliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarMouseReleased

    private void btn_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseClicked
        // TODO add your handling code here:
        btn_modificar.setBackground(Color.black);
        btn_nuevo.setBackground(Color.red);
        btn_ver.setBackground(Color.black);
        modificar=false;
        nuevo=true;
        modoSinDatos();
        cambiarModo();
        txt_codigo.requestFocus();
    }//GEN-LAST:event_btn_nuevoMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        // TODO add your handling code here:
        if(productoActual.size()>0)
        {
            
            btn_modificar.setBackground(Color.red);
            btn_nuevo.setBackground(Color.black);
            btn_ver.setBackground(Color.black);
            modificar=true;
            nuevo=false;
            cambiarModo();
            txt_codigo.requestFocus();
            cargarProductoActual();
        }
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_modificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarMousePressed

    private void btn_modificarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_modificarMouseReleased

    private void btn_nuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoMousePressed

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Salir1MouseClicked

    private void tbl_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productosMouseClicked
        // TODO add your handling code here:
       int fila= tbl_productos.getSelectedRow();
       if(fila>-1)
       {
           cargarProducto(tbl_productos.getValueAt(fila,0).toString(),tbl_productos.getValueAt(fila,1).toString(),tbl_productos.getValueAt(fila,2).toString());
       }
    }//GEN-LAST:event_tbl_productosMouseClicked

    private void rbtn_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_CreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_CreditoActionPerformed

    private void rbtn_Credito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Credito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Credito2ActionPerformed

    private void txt_codigo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1FocusGained

    private void txt_codigo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1FocusLost

    private void txt_codigo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_codigo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1MousePressed

    private void txt_codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1ActionPerformed

    private void lbl_codigo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_codigo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_codigo1MouseClicked

    private void rbtn_CreditoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_CreditoStateChanged
        // TODO add your handling code here:
        llenarListado();
    }//GEN-LAST:event_rbtn_CreditoStateChanged

    private void rbtn_Credito1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_Credito1StateChanged
        // TODO add your handling code here:
        llenarListado();
    }//GEN-LAST:event_rbtn_Credito1StateChanged

    private void rbtn_Credito2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_Credito2StateChanged
        // TODO add your handling code here:
        llenarListado();
    }//GEN-LAST:event_rbtn_Credito2StateChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salir1;
    private javax.swing.JLabel btn_Guardar_Aceptar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel btn_modificar;
    private javax.swing.JLabel btn_nuevo;
    private javax.swing.JLabel btn_ver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_sucursal;
    private javax.swing.JComboBox<String> cmb_unidad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_codigo1;
    private javax.swing.JLabel lbl_codigoBarra;
    private javax.swing.JLabel lbl_precioVenta;
    public static javax.swing.JPanel pnContenido;
    public static javax.swing.JPanel pnDetalle;
    private javax.swing.JPanel pn_herramientas;
    private javax.swing.JRadioButton rbtn_Credito;
    private javax.swing.JRadioButton rbtn_Credito1;
    private javax.swing.JRadioButton rbtn_Credito2;
    private javax.swing.JScrollPane scp_descripcion;
    public static javax.swing.JScrollPane scp_listado;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextArea txa_descripcion;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigo1;
    private javax.swing.JTextField txt_codigoBarra;
    private javax.swing.JTextField txt_columna;
    private javax.swing.JTextField txt_costo;
    private javax.swing.JTextField txt_estanteria;
    private javax.swing.JTextField txt_existencia;
    private javax.swing.JTextField txt_fila;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_venta;
    // End of variables declaration//GEN-END:variables
}
