/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jonathan Miranda
 */
public class Compras extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores
     */
    public Compras() {
        initComponents();
        setBoton(btn_Pedidos);
        resetBoton(btn_Pagos);
        resetBoton(btn_Proveedores);
        JPanel j = new Pedidos();
        j.setLocation(0, 0);
        j.setSize(panel_Contenido.getSize());
        panel_Contenido.removeAll();
        panel_Contenido.add(j, BorderLayout.CENTER);
        panel_Contenido.revalidate();
    }
    private void setBoton(JLabel boton){
        boton.setBackground(Color.RED);
    }
    private void resetBoton(JLabel boton){
        boton.setBackground(Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Pedidos = new javax.swing.JLabel();
        btn_Proveedores = new javax.swing.JLabel();
        btn_Pagos = new javax.swing.JLabel();
        panel_Contenido = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/cancel (2).png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 40, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/minus-symbol.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        btn_Pedidos.setBackground(new java.awt.Color(0, 0, 0));
        btn_Pedidos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_Pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btn_Pedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Pedidos.setText("PEDIDOS");
        btn_Pedidos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Pedidos.setName(""); // NOI18N
        btn_Pedidos.setOpaque(true);
        btn_Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PedidosMouseClicked(evt);
            }
        });
        add(btn_Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 160, 50));

        btn_Proveedores.setBackground(new java.awt.Color(0, 0, 0));
        btn_Proveedores.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_Proveedores.setForeground(new java.awt.Color(255, 255, 255));
        btn_Proveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Proveedores.setText("PROVEEDORES");
        btn_Proveedores.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Proveedores.setName(""); // NOI18N
        btn_Proveedores.setOpaque(true);
        btn_Proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ProveedoresMouseClicked(evt);
            }
        });
        add(btn_Proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 160, 50));

        btn_Pagos.setBackground(new java.awt.Color(0, 0, 0));
        btn_Pagos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_Pagos.setForeground(new java.awt.Color(255, 255, 255));
        btn_Pagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Pagos.setText("PAGOS");
        btn_Pagos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Pagos.setName(""); // NOI18N
        btn_Pagos.setOpaque(true);
        btn_Pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PagosMouseClicked(evt);
            }
        });
        add(btn_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -10, 160, 50));

        panel_Contenido.setBackground(new java.awt.Color(0, 0, 0));
        panel_Contenido.setName(""); // NOI18N

        javax.swing.GroupLayout panel_ContenidoLayout = new javax.swing.GroupLayout(panel_Contenido);
        panel_Contenido.setLayout(panel_ContenidoLayout);
        panel_ContenidoLayout.setHorizontalGroup(
            panel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        panel_ContenidoLayout.setVerticalGroup(
            panel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        add(panel_Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 940, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_PedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PedidosMouseClicked
        setBoton(btn_Pedidos);
        resetBoton(btn_Pagos);
        resetBoton(btn_Proveedores);
        JPanel j = new Pedidos();
        j.setLocation(0, 0);
        j.setSize(panel_Contenido.getSize());
        panel_Contenido.removeAll();
        panel_Contenido.add(j, BorderLayout.CENTER);
        panel_Contenido.revalidate();
    }//GEN-LAST:event_btn_PedidosMouseClicked

    private void btn_ProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ProveedoresMouseClicked
        resetBoton(btn_Pedidos);
        resetBoton(btn_Pagos);
        setBoton(btn_Proveedores);
        JPanel j = new Proveedores();
        j.setLocation(0, 0);
        j.setSize(panel_Contenido.getSize());
        panel_Contenido.removeAll();
        panel_Contenido.add(j, BorderLayout.CENTER);
        panel_Contenido.revalidate();
    }//GEN-LAST:event_btn_ProveedoresMouseClicked

    private void btn_PagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PagosMouseClicked
        resetBoton(btn_Pedidos);
        setBoton(btn_Pagos);
        resetBoton(btn_Proveedores);
    }//GEN-LAST:event_btn_PagosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Pagos;
    private javax.swing.JLabel btn_Pedidos;
    private javax.swing.JLabel btn_Proveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel panel_Contenido;
    // End of variables declaration//GEN-END:variables
}
