/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import RobertoPruebas.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonathan Miranda
 */
public class Pedidos extends javax.swing.JPanel {

    private DefaultTableModel Productos;
    private final Conexion Conexion_DB = new Conexion();
    private final DialogodeMensaje dialogo = new DialogodeMensaje();
    public Pedidos() {
        initComponents();
        try {
            lbl_Orden.setText(Conexion_DB.numeroPedido()+"");
        } catch (SQLException ex) {
            dialogo.setContenido("ERROR", ex.getMessage(), DialogodeMensaje.ICONO_ERROR);
            dialogo.setVisible(true);
        }
    }
    private void iniciarTablaProductos() {
//        
        Productos = new DefaultTableModel(null, new String[]{"Codigo", "Descripccion", "Cantidad", "P/Unitario", "P/Total"}){
            boolean[] canEdit = new boolean [] {
        false, false, true, true, false
            };
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
            }
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detalle = new javax.swing.JTable();
        btn_Nuevo = new javax.swing.JLabel();
        btn_Consultar = new javax.swing.JLabel();
        btn_Editar = new javax.swing.JLabel();
        sep_Nombre = new javax.swing.JSeparator();
        txt_Nombre = new javax.swing.JTextField();
        lbl_Nombre = new javax.swing.JLabel();
        btn_Seleccion = new javax.swing.JLabel();
        lbl_Orden = new javax.swing.JLabel();
        txt_Factura = new javax.swing.JTextField();
        sep_Nombre1 = new javax.swing.JSeparator();
        lbl_Nombre2 = new javax.swing.JLabel();
        lbl_Nombre3 = new javax.swing.JLabel();
        lbl_Deuda = new javax.swing.JLabel();
        txt_Total = new javax.swing.JTextField();
        sep_Deuda = new javax.swing.JSeparator();
        lbl_Deuda1 = new javax.swing.JLabel();
        txt_Deuda1 = new javax.swing.JTextField();
        sep_Deuda1 = new javax.swing.JSeparator();
        lbl_Deuda2 = new javax.swing.JLabel();
        txt_Deuda2 = new javax.swing.JTextField();
        sep_Deuda2 = new javax.swing.JSeparator();
        rbtn_Credito = new javax.swing.JRadioButton();
        btn_Seleccion1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_detalle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabla_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_detalle.setGridColor(new java.awt.Color(0, 0, 0));
        tabla_detalle.setRowHeight(24);
        tabla_detalle.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tabla_detalle.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabla_detalle.setShowVerticalLines(false);
        tabla_detalle.getTableHeader().setReorderingAllowed(false);
        tabla_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_detalleMousePressed(evt);
            }
        });
        tabla_detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_detalleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_detalleKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_detalle);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 349, 940, 300));

        btn_Nuevo.setBackground(new java.awt.Color(255, 0, 0));
        btn_Nuevo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Nuevo.setText("NUEVO");
        btn_Nuevo.setOpaque(true);
        btn_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoMouseClicked(evt);
            }
        });
        add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 300, 84));

        btn_Consultar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Consultar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_Consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Consultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Consultar.setText("CONSULTAR");
        btn_Consultar.setOpaque(true);
        btn_Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConsultarMouseClicked(evt);
            }
        });
        add(btn_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 300, 84));

        btn_Editar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Editar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_Editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Editar.setText("EDITAR");
        btn_Editar.setOpaque(true);
        btn_Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditarMouseClicked(evt);
            }
        });
        add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 300, 84));

        sep_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        add(sep_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 400, 10));

        txt_Nombre.setEditable(false);
        txt_Nombre.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nombre.setText("PROVEEDOR");
        txt_Nombre.setBorder(null);
        txt_Nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Nombre.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NombreFocusLost(evt);
            }
        });
        txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NombreMousePressed(evt);
            }
        });
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 26));

        lbl_Nombre.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre.setText("PROVEEDOR");
        add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btn_Seleccion.setBackground(new java.awt.Color(255, 0, 0));
        btn_Seleccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccion.setForeground(new java.awt.Color(255, 255, 255));
        btn_Seleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccion.setText("SELECCIONAR");
        btn_Seleccion.setEnabled(false);
        btn_Seleccion.setOpaque(true);
        btn_Seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SeleccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SeleccionMouseEntered(evt);
            }
        });
        add(btn_Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 90, 30));

        lbl_Orden.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Orden.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Orden.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Orden.setText("000001");
        add(lbl_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        txt_Factura.setBackground(new java.awt.Color(0, 0, 0));
        txt_Factura.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Factura.setForeground(new java.awt.Color(255, 255, 255));
        txt_Factura.setText("INGRESE NUEMERO DE FACTURA");
        txt_Factura.setBorder(null);
        txt_Factura.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Factura.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Factura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FacturaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FacturaFocusLost(evt);
            }
        });
        txt_Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_FacturaMousePressed(evt);
            }
        });
        txt_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FacturaActionPerformed(evt);
            }
        });
        add(txt_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, 26));

        sep_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        add(sep_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 400, 10));

        lbl_Nombre2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre2.setText("FACTURA");
        add(lbl_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lbl_Nombre3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre3.setText("ORDEN NO.");
        add(lbl_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        lbl_Deuda.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Deuda.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Deuda.setText("TOTAL");
        add(lbl_Deuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        txt_Total.setBackground(new java.awt.Color(0, 0, 0));
        txt_Total.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Total.setForeground(new java.awt.Color(255, 255, 255));
        txt_Total.setText("0.00");
        txt_Total.setBorder(null);
        txt_Total.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Total.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txt_Total.setEnabled(false);
        txt_Total.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Total.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TotalFocusLost(evt);
            }
        });
        txt_Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_TotalMousePressed(evt);
            }
        });
        txt_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalActionPerformed(evt);
            }
        });
        add(txt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 220, 26));

        sep_Deuda.setForeground(new java.awt.Color(255, 255, 255));
        add(sep_Deuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 220, -1));

        lbl_Deuda1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Deuda1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Deuda1.setText("ABONOS");
        add(lbl_Deuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        txt_Deuda1.setBackground(new java.awt.Color(0, 0, 0));
        txt_Deuda1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Deuda1.setForeground(new java.awt.Color(255, 255, 255));
        txt_Deuda1.setText("0.00");
        txt_Deuda1.setBorder(null);
        txt_Deuda1.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Deuda1.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txt_Deuda1.setEnabled(false);
        txt_Deuda1.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Deuda1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Deuda1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Deuda1FocusLost(evt);
            }
        });
        txt_Deuda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Deuda1MousePressed(evt);
            }
        });
        txt_Deuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Deuda1ActionPerformed(evt);
            }
        });
        add(txt_Deuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 130, 26));

        sep_Deuda1.setForeground(new java.awt.Color(255, 255, 255));
        add(sep_Deuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 220, -1));

        lbl_Deuda2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Deuda2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Deuda2.setText("SALDO");
        add(lbl_Deuda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        txt_Deuda2.setBackground(new java.awt.Color(0, 0, 0));
        txt_Deuda2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_Deuda2.setForeground(new java.awt.Color(255, 255, 255));
        txt_Deuda2.setText("0.00");
        txt_Deuda2.setBorder(null);
        txt_Deuda2.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Deuda2.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txt_Deuda2.setEnabled(false);
        txt_Deuda2.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Deuda2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Deuda2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Deuda2FocusLost(evt);
            }
        });
        txt_Deuda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Deuda2MousePressed(evt);
            }
        });
        txt_Deuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Deuda2ActionPerformed(evt);
            }
        });
        add(txt_Deuda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 220, 26));

        sep_Deuda2.setForeground(new java.awt.Color(255, 255, 255));
        add(sep_Deuda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 220, -1));

        rbtn_Credito.setBackground(new java.awt.Color(0, 0, 0));
        rbtn_Credito.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbtn_Credito.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_Credito.setSelected(true);
        rbtn_Credito.setText("CREDITO");
        rbtn_Credito.setBorder(null);
        add(rbtn_Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 400, -1));

        btn_Seleccion1.setBackground(new java.awt.Color(255, 0, 0));
        btn_Seleccion1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccion1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Seleccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccion1.setText("PAGOS");
        btn_Seleccion1.setEnabled(false);
        btn_Seleccion1.setOpaque(true);
        btn_Seleccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Seleccion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Seleccion1MouseEntered(evt);
            }
        });
        add(btn_Seleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoMouseClicked
        if (btn_Consultar.getText().equals("CONSULTAR")) {
            iniciarTablaProductos();
            Productos.addRow(new String[]{});
            tabla_detalle.setModel(Productos);
            btn_Seleccion.setEnabled(true);
            btn_Consultar.setText("GUARDAR");
            btn_Editar.setText("CANCELAR");
            try {
            lbl_Orden.setText(Conexion_DB.numeroPedido()+"");
        } catch (SQLException ex) {
            dialogo.setContenido("ERROR", ex.getMessage(), DialogodeMensaje.ICONO_ERROR);
            dialogo.setVisible(true);
        }
        }
        
    }//GEN-LAST:event_btn_NuevoMouseClicked

    private void btn_ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultarMouseClicked
        if (btn_Consultar.getText().equals("GUARDAR")) {
            try {
                if (!txt_Nombre.getText().equals("PROVEEDOR") && !txt_Nombre.getText().equals("")) {
                    Conexion_DB.crearPedido(((txt_Factura.getText().equals("INGRESE NUEMERO DE FACTURA")) ? "": txt_Factura.getText()), total, rbtn_Credito.isSelected());
                    dialogo.setContenido("INFORMACION", "SE A GUARDADO EXITOSAMENTE", DialogodeMensaje.ICONO_INFORMACION);
                    dialogo.setVisible(true);
                    lbl_Orden.setText(Conexion_DB.numeroPedido()+"");
                    for (int i = 0; i < tabla_detalle.getRowCount() - 1; i++) {
                        Conexion_DB.insertarDetallePedido(Conexion_DB.idCodigo(tabla_detalle.getValueAt(i, 0).toString()), Conexion_DB.idProve(txt_Nombre.getText()), Conexion_DB.numeroPedido(), Float.parseFloat(tabla_detalle.getValueAt(i, 3).toString()), Float.parseFloat(tabla_detalle.getValueAt(i, 2).toString()));
                    }
                }else{
                    dialogo.setContenido("INFORMACION", "SELECCIONE UN PROVEEDOR", DialogodeMensaje.ICONO_INFORMACION);
                    dialogo.setVisible(true);
                }
                
            } catch (SQLException ex) {
                dialogo.setContenido("ERROR", ex.getMessage(), DialogodeMensaje.ICONO_ERROR);
                dialogo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_ConsultarMouseClicked

    private void btn_EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditarMouseClicked

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreMousePressed

    private void txt_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusLost
        if (txt_Nombre.getText().equals("")) txt_Nombre.setText("INGRESE EL NOMBRE DEL PROVEEDOR");
    }//GEN-LAST:event_txt_NombreFocusLost

    private void txt_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusGained
        if (txt_Nombre.getText().equals("INGRESE EL NOMBRE DEL PROVEEDOR")) txt_Nombre.setText("");
    }//GEN-LAST:event_txt_NombreFocusGained

    private void btn_SeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionMouseClicked
        selectorProveedor selector = new selectorProveedor();
        selector.setTxt(txt_Nombre);
        selector.setVisible(true);

    }//GEN-LAST:event_btn_SeleccionMouseClicked

    private void btn_SeleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SeleccionMouseEntered

    private void txt_FacturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FacturaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaFocusGained

    private void txt_FacturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FacturaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaFocusLost

    private void txt_FacturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FacturaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaMousePressed

    private void txt_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaActionPerformed

    private void txt_TotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TotalFocusGained
        // TODO add your handling code here:
        if(txt_Total.getText().equals("INGRESE EL NOMBRE DE USUARIO"))txt_Total.setText("");
    }//GEN-LAST:event_txt_TotalFocusGained

    private void txt_TotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TotalFocusLost
        // TODO add your handling code here:
        if(txt_Total.getText().equals("")) txt_Total.setText("INGRESE EL NOMBRE DE USUARIO");
    }//GEN-LAST:event_txt_TotalFocusLost

    private void txt_TotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TotalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalMousePressed

    private void txt_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalActionPerformed

    private void txt_Deuda1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Deuda1FocusGained
        // TODO add your handling code here:
        if(txt_Total.getText().equals("INGRESE EL NOMBRE DE USUARIO"))txt_Total.setText("");
    }//GEN-LAST:event_txt_Deuda1FocusGained

    private void txt_Deuda1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Deuda1FocusLost
        // TODO add your handling code here:
        if(txt_Total.getText().equals("")) txt_Total.setText("INGRESE EL NOMBRE DE USUARIO");
    }//GEN-LAST:event_txt_Deuda1FocusLost

    private void txt_Deuda1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Deuda1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Deuda1MousePressed

    private void txt_Deuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Deuda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Deuda1ActionPerformed

    private void txt_Deuda2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Deuda2FocusGained
        // TODO add your handling code here:
        if(txt_Total.getText().equals("INGRESE EL NOMBRE DE USUARIO"))txt_Total.setText("");
    }//GEN-LAST:event_txt_Deuda2FocusGained

    private void txt_Deuda2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Deuda2FocusLost
        // TODO add your handling code here:
        if(txt_Total.getText().equals("")) txt_Total.setText("INGRESE EL NOMBRE DE USUARIO");
    }//GEN-LAST:event_txt_Deuda2FocusLost

    private void txt_Deuda2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Deuda2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Deuda2MousePressed

    private void txt_Deuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Deuda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Deuda2ActionPerformed

    private void btn_Seleccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Seleccion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Seleccion1MouseClicked

    private void btn_Seleccion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Seleccion1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Seleccion1MouseEntered

    private void tabla_detalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_detalleKeyPressed
       
    }//GEN-LAST:event_tabla_detalleKeyPressed
    private float total = 0;
    private void tabla_detalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_detalleKeyReleased
        if(btn_Consultar.getText().equals("GUARDAR")){
            if (evt.getKeyCode() == 112) {
                selectorProducto selector = new selectorProducto();
                selector.setProductos(Productos);
                selector.setVisible(true);
            }
            if (evt.getKeyCode() == 114) {
                if (Productos.getRowCount()>1) {
                    Productos.removeRow(tabla_detalle.getSelectedRow());
                    total();
                }

            }
            if (evt.getKeyCode() == 38) {
                int seleccion = tabla_detalle.getSelectedRow() + 1;
                float cantidad = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 2).toString());
                float precio = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 3).toString());
                tabla_detalle.setValueAt("" + (cantidad * precio), seleccion, 4);
                total();
            }
            if (evt.getKeyCode() == 40 || evt.getKeyCode() ==13 || evt.getKeyCode() == 9) {
                int seleccion = tabla_detalle.getSelectedRow() - 1;
                float cantidad = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 2).toString());
                float precio = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 3).toString());
                tabla_detalle.setValueAt("" + (cantidad * precio), seleccion, 4);
                total();
            }
        }
    }//GEN-LAST:event_tabla_detalleKeyReleased
    private void total(){
        int cant = tabla_detalle.getRowCount() - 1;
        total =0;
        for (int i = 0; i < cant; i++) {
            total += Float.parseFloat(tabla_detalle.getValueAt(i, 4).toString());
        }
        txt_Total.setText(total+"");
    }
    private void tabla_detalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_detalleMousePressed
        
    }//GEN-LAST:event_tabla_detalleMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Consultar;
    private javax.swing.JLabel btn_Editar;
    private javax.swing.JLabel btn_Nuevo;
    private javax.swing.JLabel btn_Seleccion;
    private javax.swing.JLabel btn_Seleccion1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Deuda;
    private javax.swing.JLabel lbl_Deuda1;
    private javax.swing.JLabel lbl_Deuda2;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Nombre2;
    private javax.swing.JLabel lbl_Nombre3;
    private javax.swing.JLabel lbl_Orden;
    private javax.swing.JRadioButton rbtn_Credito;
    private javax.swing.JSeparator sep_Deuda;
    private javax.swing.JSeparator sep_Deuda1;
    private javax.swing.JSeparator sep_Deuda2;
    private javax.swing.JSeparator sep_Nombre;
    private javax.swing.JSeparator sep_Nombre1;
    private javax.swing.JTable tabla_detalle;
    private javax.swing.JTextField txt_Deuda1;
    private javax.swing.JTextField txt_Deuda2;
    private javax.swing.JTextField txt_Factura;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables
}
